### ISSUE TITLE
Error on execute

### ISSUE THREAD

**Issue by silfar** [mkl-public/testarea-pdfbox2#10]
![Capturar](https://user-images.githubusercontent.com/68900/114314901-fb02b380-9ad2-11eb-9c5d-d191fe18af19.PNG)
Hello, I'm trying to run the tests and I always get the error attached. Can you help me ?

**Comment by mkl-public** [comment]
The stack trace says that it cannot find `mkl.testarea.pdfbox2.extract.ExtractBoxedText`. But that is the class the test you show above is in. Thus, either your IDE has incorrectly loaded the project, or you start the test incorrectly, or you have changed the project in a relevant way.

**Comment by silfar** [comment]
This is strange, I didn't change the project, I'm using vscode as an IDE.

**Comment by mkl-public** [comment]
I'm afraid I cannot help with vscode; I haven't had more than a quick glance at it, and I have not used it at all with Java.
