### ISSUE TITLE
Tables with Merged cells

### ISSUE THREAD

**Issue by pdob-git** [mkl-public/testarea-pdfbox2#14]
### Tables with Merged cells ###
I'm traying to resolve issue from question on stackoverflow. Any help would be appreciated
[Tables with Merged cells question 78001237](https://stackoverflow.com/questions/78001237/extracting-text-from-pdf-java-using-pdfbox-library-from-a-tables-with-merged-c)

**Comment by mkl-public** [comment]
According to your own answer there you have solved the issue for your use case.

https://github.com/pdob-git/testarea-pdfbox2/blob/master/src/main/java/pl/pdob/pdftables/MainDemo.java
