### ISSUE TITLE
How to Attach an Image to a PDF Form Field Without Invalidating an Existing Signature?

### ISSUE THREAD

**Issue by shivammalviya71234** [mkl-public/testarea-pdfbox2#18]
Usecase: I'm working on a feature that requires attaching an image to a PDF without invalidating a pre-existing digital signature. The PDF should have a form field designated for image attachment, which can be populated later. I want to implement this using PDFBox.

Implementation: Since PDFs lack a dedicated image form field, I’m utilizing a PDPushButton as a workaround, following the method outlined in the following issue;
- https://github.com/mkl-public/testarea-pdfbox2/issues/1

Additionally, the PDF includes a signature form field. The process involves signing the signature field first and subsequently attaching the image to the PDPushButton field. However, this sequence is causing the signature to become invalid.

Here is the code for attaching an image to the PDPushButton.
```
@SneakyThrows
public static void fillInitialField(String inputFilePath, String outputFilePath) {
    // Load input file
    PDDocument document = PDDocument.load(new File(inputFilePath));

    // Find and link the relevant signature field
    PDPushButton initial = PdfService.findInitial(document, "132323423180965");

    PDImageXObject pdImageXObject = PDImageXObject.createFromFile("initial.png", document);
    float width = 10 * pdImageXObject.getWidth();
    float height = 10 * pdImageXObject.getHeight();

    PDAppearanceStream pdAppearanceStream = new PDAppearanceStream(document);
    pdAppearanceStream.setResources(new PDResources());
    try (PDPageContentStream pdPageContentStream = new PDPageContentStream(document, pdAppearanceStream)) {
        pdPageContentStream.drawImage(pdImageXObject, 200, 300, width, height);
    }
    pdAppearanceStream.setBBox(new PDRectangle(width, height));

    List<PDAnnotationWidget> widgets = initial.getWidgets();
    for (PDAnnotationWidget pdAnnotationWidget : widgets) {

        PDAppearanceDictionary pdAppearanceDictionary = pdAnnotationWidget.getAppearance();
        if (pdAppearanceDictionary == null) {
            pdAppearanceDictionary = new PDAppearanceDictionary();
            pdAnnotationWidget.setAppearance(pdAppearanceDictionary);
        }

        pdAppearanceDictionary.setNormalAppearance(pdAppearanceStream);
    }
    initial.setReadOnly(true);

    // Save and close the document
    FileOutputStream fos = new FileOutputStream(outputFilePath);
    document.save(fos);
    document.close();
}
```

I’ve created a repository that replicates this issue, which can be found here: https://github.com/ContractSPAN/ImageFormFieldIssue

How can I implement an image attachment to a PDF form field in such a way that it doesn’t invalidate an existing signature? I am open to alternative approaches to achieve this functionality.

**Comment by mkl-public** [comment]
You do a regular `save` at the end of `fillInitialField`. A regular `save` will re-arrange and change the signed byte range. Thus, you will need to do a `saveIncremental` like you do at the end of `sign`. 
Beware, though, a `saveIncremental` requires you to mark (`setNeedToBeUpdated(true)`) all changed objects including a sequence of objects leading to them respectively from the trailer. In case of signing a lot of that marking already is done by PDFBox itself. In your `fillInitialField` method you'll have to do all the marking yourself.

**Comment by shivammalviya71234** [comment]
Thanks mkl for the quick response! 
Using the saveIncremental helped to keep the validity of the signature. However, the attached image to PDPushButton isn't visible in the Adobe PDF viewer, as well as in the libredraw. Here is that PDF. 
[signedAndImageFilledPdf.pdf](https://github.com/mkl-public/testarea-pdfbox2/files/14974050/signedAndImageFilledPdf.pdf)

I tried to mark NeedToBeUpdated true for the chain of changed objects.  Although, in my case, for some reason, there is no parent of the PDPushButton. 
![image](https://github.com/mkl-public/testarea-pdfbox2/assets/130989700/944fe4fb-c493-4202-91a4-3ae7a07aaee5)

Below is the modified code which I used. I have also pushed it into the [repository](https://github.com/ContractSPAN/ImageFormFieldIssue)
```
@SneakyThrows
public static void fillInitialField(String inputFilePath, String outputFilePath) {
    // Load input file
    PDDocument document = PDDocument.load(new File(inputFilePath));

    // Find and link the relevant signature field
    PDPushButton initial = PdfService.findInitial(document, "132323423180965");

    PDImageXObject pdImageXObject = PDImageXObject.createFromFile("initial.png", document);
    float width = 10 * pdImageXObject.getWidth();
    float height = 10 * pdImageXObject.getHeight();

    PDAppearanceStream pdAppearanceStream = new PDAppearanceStream(document);
    pdAppearanceStream.setResources(new PDResources());
    try (PDPageContentStream pdPageContentStream = new PDPageContentStream(document, pdAppearanceStream)) {
        pdPageContentStream.drawImage(pdImageXObject, 200, 300, width, height);
    }
    pdAppearanceStream.setBBox(new PDRectangle(width, height));

    List<PDAnnotationWidget> widgets = initial.getWidgets();
    for (PDAnnotationWidget pdAnnotationWidget : widgets) {

        PDAppearanceDictionary pdAppearanceDictionary = pdAnnotationWidget.getAppearance();
        if (pdAppearanceDictionary == null) {
            pdAppearanceDictionary = new PDAppearanceDictionary();
            pdAnnotationWidget.setAppearance(pdAppearanceDictionary);
        }

        pdAppearanceDictionary.setNormalAppearance(pdAppearanceStream);
    }
    initial.setReadOnly(true);

    // Mark (setNeedToBeUpdated(true)) all changed objects including a sequence of objects leading to them respectively from the trailer
    initial.getCOSObject().setNeedToBeUpdated(true);
    initial.getWidgets().get(0).getAppearance().getCOSObject().setNeedToBeUpdated(true);
    pdAppearanceStream.getCOSObject().setNeedToBeUpdated(true);
    pdAppearanceStream.getResources().getCOSObject().setNeedToBeUpdated(true);
    
    document.getPage(0).getCOSObject().setNeedToBeUpdated(true);
    COSDictionary docDictionary = document.getDocumentCatalog().getCOSObject();
    docDictionary.setNeedToBeUpdated(true);
    docDictionary = (COSDictionary) docDictionary.getDictionaryObject(COSName.ACRO_FORM);
    docDictionary.setNeedToBeUpdated(true);
    COSArray array = (COSArray) docDictionary.getDictionaryObject(COSName.FIELDS);
    document.getDocumentCatalog().getCOSObject().getDictionaryObject(COSName.FIELDS);
    array.setNeedToBeUpdated(true);

    COSDictionary fieldDictionary = initial.getCOSObject();
    COSDictionary dictionary = (COSDictionary) fieldDictionary.getDictionaryObject(COSName.AP);
    dictionary.setNeedToBeUpdated(true);
    COSStream stream = (COSStream) dictionary.getDictionaryObject(COSName.N);
    stream.setNeedToBeUpdated(true);
    while (fieldDictionary != null)
    {
        fieldDictionary.setNeedToBeUpdated(true);
        fieldDictionary = (COSDictionary) fieldDictionary.getDictionaryObject(COSName.PARENT);
    }

    // Save and close the document
    FileOutputStream fos = new FileOutputStream(outputFilePath);
    document.saveIncremental(fos);
    document.close();
}
```

Do I still need to mark (setNeedToBeUpdated(true)) all the chains of changed objects if I switch to PDFBox 3? I read your comment in the following [StackOverflow post](https://stackoverflow.com/questions/42802996/pdfbox-form-fill-saveincremental-does-not-work) that it is not required to mark the need to be updated in the case of PDFBox 3.
![image](https://github.com/mkl-public/testarea-pdfbox2/assets/130989700/c1c696ad-b4cd-4d2c-a0f9-82e6aaa782ff).

I tried switching to PDFBox 3 but here as well I am unable to see the attached image to the PDPushbutton in LibreDraw and Adobe. Here is the PDF file with the attached image 
[signedAndImageFilledPdf.pdf](https://github.com/mkl-public/testarea-pdfbox2/files/14974107/signedAndImageFilledPdf.pdf)
 
I have attached the code using PDFBox 3 in the PDFBox3 branch.
- https://github.com/ContractSPAN/ImageFormFieldIssue/tree/PDFBox3

Thank you so much for the help!!

**Comment by shivammalviya71234** [comment]
I was using same name for the PDPushButton and PDSignatureField leading to this issue.

Thanks mkl for all the help!
- https://stackoverflow.com/questions/78320321/how-to-attach-an-image-to-a-pdf-form-field-without-invalidating-an-existing-sign/

**Comment by shivammalviya71234** [comment]
I am closing this issue as it is resolved!
