### ISSUE TITLE
FreeSpaceFinder - PDFBox 3

### ISSUE THREAD

**Issue by fabiosallesmonteiro** [mkl-public/testarea-pdfbox2#19]
Greetings,
I found out your FreeSpaceFinder solution (src/main/java/mkl/testarea/pdfbox2/extract/FreeSpaceFinder.java), but it doesn't work with PDFBox version 3. Is there any chance you could provide an updated version to work with PDFBox 3?
I really don't have the knowledge to do that.

**Comment by mkl-public** [comment]
Hello Fabio,

I'm currently pretty busy but may take a look at that in the future.

Can you already indicate in which way it doesn't work? Is it not compilable? Or does it return something wrong?

Regards!

**Comment by fabiosallesmonteiro** [comment]
Hi,
It compiles, no errors. I did some more tests and I think the problem is my test file that has a border around the document, so FreeSpaceFinder doesn't indicate any free space.  My bad, sorry.
