### ISSUE TITLE
Performance improvement for OptimizeAfterMerge

### ISSUE THREAD

**Issue by jchobantonov** [mkl-public/testarea-pdfbox2#5]
I have tested the code with 50k pages in a pdf
The total time it took was 3:10 min

If you change in equals() method following code on line 292:

```
if (keys.equals(bDict.keySet())) {
```

with this:

```
if (keys.size() == bDict.keySet().size()) {
```
then it takes only 1:08 min. The logic of the code is the same because once we see if the 2 sets are with equal size then we are comparing inside the if statement each element in the first set with the element in the second one - if the second one do not have the key then the value would be null and the comparison won't happen and it will return false on line 295

**Comment by mkl-public** [comment]
Thank you for the proposal. Yes, with the current key-by-key comparison inside the `if` we only need to compare key set sizes. I changed the code accordingly and will close the issue.

At the same time, though, I saw that there might be a possible `NullPointerException` waiting to occur inside the `if` body if `resolve` returns `null`. That case is unlikely but not impossible, a reference to an indirect object that isn't there.

**Comment by jchobantonov** [comment]
@mkl-public Thanks, also I just noticed the code is like this:
```
if (!resolve(aDict.getItem(key)).equals(bDict.getItem(key)))
```

shouldn't the bDict.getItem also be wrapped with resolve as in the case of COSArray? like this:
```
if (!resolve(aDict.getItem(key)).equals(resolve(bDict.getItem(key))))
```

**Comment by jchobantonov** [comment]
Here is what I did to fix the possible NullPointerException and I guess to wrapp the bDict.getItem in resolve method as well:
```
    protected static boolean equals(COSBase a, COSBase b) {
        if (a instanceof COSArray) {
            if (b instanceof COSArray) {
                COSArray aArray = (COSArray) a;
                COSArray bArray = (COSArray) b;
                if (aArray.size() == bArray.size()) {
                    for (int i=0; i < aArray.size(); i++) {
                        COSBase aCosBase = resolve(aArray.get(i));
                        COSBase bCosBase = resolve(bArray.get(i));
                        if (aCosBase == null) {
                            if (bCosBase != null) {
                                return false;
                            }
                        } else {
                            if (!aCosBase.equals(bCosBase)) {
                                return false;
                            }
                        }
                    }
                    return true;
                }
            }
        } else if (a instanceof COSDictionary) {
            if (b instanceof COSDictionary) {
                COSDictionary aDict = (COSDictionary) a;
                COSDictionary bDict = (COSDictionary) b;
                Set<COSName> keys = aDict.keySet();
                if (keys.size() == bDict.keySet().size()) {
                    for (COSName key : keys) {
                        COSBase aCosBase = resolve(aDict.getItem(key));
                        COSBase bCosBase = resolve(bDict.getItem(key));
                        if (aCosBase == null) {
                            if (bCosBase != null) {
                                return false;
                            }
                        } else {
                            if (!aCosBase.equals(bCosBase)) {
                                return false;
                            }
                        }
                    }
                    // In case of COSStreams we strictly speaking should
                    // also compare the stream contents here. But apparently
                    // their hashes coincide well enough for the original
                    // hashing equality, so let's just assume...
                    return true;
                }
            }
        }
        return false;
    }
```

**Comment by jchobantonov** [comment]
I did just tried out the bDict.getItem() wrapper in resolve and it did not worked out correctly - so I guess my assumption was wrong that bDict.getItem need to be wrapped into resolve().

here is the code that should fix the NullPointerException only :
```
    protected static boolean equals(COSBase a, COSBase b) {
        if (a instanceof COSArray) {
            if (b instanceof COSArray) {
                COSArray aArray = (COSArray) a;
                COSArray bArray = (COSArray) b;
                if (aArray.size() == bArray.size()) {
                    for (int i=0; i < aArray.size(); i++) {
                        COSBase aCosBase = resolve(aArray.get(i));
                        COSBase bCosBase = resolve(bArray.get(i));
                        if (aCosBase == null) {
                            if (bCosBase != null) {
                                return false;
                            }
                        } else {
                            if (!aCosBase.equals(bCosBase)) {
                                return false;
                            }
                        }
                    }
                    return true;
                }
            }
        } else if (a instanceof COSDictionary) {
            if (b instanceof COSDictionary) {
                COSDictionary aDict = (COSDictionary) a;
                COSDictionary bDict = (COSDictionary) b;
                Set<COSName> keys = aDict.keySet();
                if (keys.size() == bDict.keySet().size()) {
                    for (COSName key : keys) {
                        COSBase aCosBase = resolve(aDict.getItem(key));
                        COSBase bCosBase = bDict.getItem(key);
                        if (aCosBase == null) {
                            if (bCosBase != null) {
                                return false;
                            }
                        } else {
                            if (!aCosBase.equals(bCosBase)) {
                                return false;
                            }
                        }
                    }
                    // In case of COSStreams we strictly speaking should
                    // also compare the stream contents here. But apparently
                    // their hashes coincide well enough for the original
                    // hashing equality, so let's just assume...
                    return true;
                }
            }
        }
        return false;
    }
```

**Comment by jchobantonov** [comment]
@mkl-public not the question is should the equals method for the COSArray if section be like this:

COSBase bCosBase = resolve(bArray.get(i));

or be like this:
COSBase bCosBase = bArray.get(i);

e.g. without resolve method wrapping the bArray.get(i) that will mirror the bDict part of the equals method. - if I do not wrap the bArray into resolve the pdf will slightly bump it size at the end.

**Comment by jchobantonov** [comment]
@mkl-public 

Could we actually replace the keys.size with the COSDictionary.size() as they are the same but underneath  aDict.keySet() it uses SmartMap so it will create a new Set which is unnecessary if the dictionary size are not the same - e.g. the dictionary size is equal to the key size - so we could check only the dictionary size like this:
```
if (aDict.size() == bDict.size()) {
       Set<COSName> keys = aDict.keySet();
       for (COSName key : keys) {
           ....
       }
}
```

also instead of having this signature of the mergeRun method we could have it like this:
```
    mergeRun(Map<COSBase, Collection<Reference>> complexObjects, List<HashOfCOSBase> run, int runStartIndex, int runEndIndex) {
```

e.g. to pass the start index and end index for the run List instead of creating a new subList from the run first and then pass only the sub list portion

**Comment by mkl-public** [comment]
>Could we actually replace the `keys.size` with the `COSDictionary.size()` ...

Yes, you can pull the key set retrieval into the `if` block this way. That key set retrieval can indeed be an expensive operation. Actually one could make the `keyset` method much less expensive by implementing a custom set class that operates on the underlying `mapArr` of the `smallMap`...

>also instead of having this signature of the `mergeRun` method we could have it like this

You can but that won't win quite as much as the change above (at least I think so) as this sub list creation is not very expensive and also O(1).
