### ISSUE TITLE
how to modify form object  stream?

### ISSUE THREAD

**Issue by zhongguogu** [mkl-public/testarea-pdfbox2#9]
https://github.com/mkl-public/testarea-pdfbox2/blob/master/src/test/java/mkl/testarea/pdfbox2/content/RemoveText.java#L49
`
    public void processForm(PDFormXObject form) throws IOException {
   
        final PDStream formContentStream = form.getContentStream();
        final PDResources resources = form.getResources();
        formReplacementStream=formContentStream.createOutputStream(COSName.FLATE_DECODE);
        formReplacement = new ContentStreamWriter(formReplacementStream);
        super.showForm(form);

    }
`
how to update the PDFormXObjects'  stream?

**Comment by zhongguogu** [comment]
"Indeed, I would create a new form XObject and replace the reference to the old one in the page resources by a reference to the new one"

**Comment by mkl-public** [comment]
Please share an example PDF for testing that.

**Comment by mkl-public** [comment]
Closing due to missing response
